/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "BaseCRLNumber.h"

int
BaseCRLNumber_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const CRLNumber_t *st = (const CRLNumber_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Check if the sign bit is present */
	value = st->buf ? ((st->buf[0] & 0x80) ? -1 : 1) : 0;
	
	if((value >= 0)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using CRLNumber,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_BaseCRLNumber_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_BaseCRLNumber = {
	"BaseCRLNumber",
	"BaseCRLNumber",
	&asn_OP_INTEGER,
	BaseCRLNumber_constraint,
	asn_DEF_BaseCRLNumber_tags_1,
	sizeof(asn_DEF_BaseCRLNumber_tags_1)
		/sizeof(asn_DEF_BaseCRLNumber_tags_1[0]), /* 1 */
	asn_DEF_BaseCRLNumber_tags_1,	/* Same as above */
	sizeof(asn_DEF_BaseCRLNumber_tags_1)
		/sizeof(asn_DEF_BaseCRLNumber_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	0	/* No specifics */
};

