/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_CountryOfResidence_H_
#define	_CountryOfResidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CountryOfResidence */
typedef PrintableString_t	 CountryOfResidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CountryOfResidence;
asn_struct_free_f CountryOfResidence_free;
asn_struct_print_f CountryOfResidence_print;
asn_constr_check_f CountryOfResidence_constraint;
ber_type_decoder_f CountryOfResidence_decode_ber;
der_type_encoder_f CountryOfResidence_encode_der;
xer_type_decoder_f CountryOfResidence_decode_xer;
xer_type_encoder_f CountryOfResidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CountryOfResidence_H_ */
#include <asn_internal.h>
