/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_DateOfBirth_H_
#define	_DateOfBirth_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralizedTime.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DateOfBirth */
typedef GeneralizedTime_t	 DateOfBirth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DateOfBirth;
asn_struct_free_f DateOfBirth_free;
asn_struct_print_f DateOfBirth_print;
asn_constr_check_f DateOfBirth_constraint;
ber_type_decoder_f DateOfBirth_decode_ber;
der_type_encoder_f DateOfBirth_encode_der;
xer_type_decoder_f DateOfBirth_decode_xer;
xer_type_encoder_f DateOfBirth_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DateOfBirth_H_ */
#include <asn_internal.h>
