/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "DateOfBirth.h"

/*
 * This type is implemented using GeneralizedTime,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_DateOfBirth_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (24 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DateOfBirth = {
	"DateOfBirth",
	"DateOfBirth",
	&asn_OP_GeneralizedTime,
	GeneralizedTime_constraint,
	asn_DEF_DateOfBirth_tags_1,
	sizeof(asn_DEF_DateOfBirth_tags_1)
		/sizeof(asn_DEF_DateOfBirth_tags_1[0]), /* 1 */
	asn_DEF_DateOfBirth_tags_1,	/* Same as above */
	sizeof(asn_DEF_DateOfBirth_tags_1)
		/sizeof(asn_DEF_DateOfBirth_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	0	/* No specifics */
};

