/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms88"
 * 	found in "asn1/rfc3279-PKIX1Algorithms88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_EcpkParameters_H_
#define	_EcpkParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECParameters.h"
#include <OBJECT_IDENTIFIER.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EcpkParameters_PR {
	EcpkParameters_PR_NOTHING,	/* No components present */
	EcpkParameters_PR_ecParameters,
	EcpkParameters_PR_namedCurve,
	EcpkParameters_PR_implicitlyCA
} EcpkParameters_PR;

/* EcpkParameters */
typedef struct EcpkParameters {
	EcpkParameters_PR present;
	union EcpkParameters_u {
		ECParameters_t	 ecParameters;
		OBJECT_IDENTIFIER_t	 namedCurve;
		NULL_t	 implicitlyCA;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EcpkParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcpkParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _EcpkParameters_H_ */
#include <asn_internal.h>
