/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms88"
 * 	found in "asn1/rfc3279-PKIX1Algorithms88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_ECPVer_H_
#define	_ECPVer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ECPVer {
	ECPVer_ecpVer1	= 1
} e_ECPVer;

/* ECPVer */
typedef INTEGER_t	 ECPVer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECPVer;
asn_struct_free_f ECPVer_free;
asn_struct_print_f ECPVer_print;
asn_constr_check_f ECPVer_constraint;
ber_type_decoder_f ECPVer_decode_ber;
der_type_encoder_f ECPVer_encode_der;
xer_type_decoder_f ECPVer_decode_xer;
xer_type_encoder_f ECPVer_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ECPVer_H_ */
#include <asn_internal.h>
