/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc3280-PKIX1Explicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_ExtensionORAddressComponents_H_
#define	_ExtensionORAddressComponents_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDSParameter.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ExtensionORAddressComponents */
typedef PDSParameter_t	 ExtensionORAddressComponents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtensionORAddressComponents;
asn_struct_free_f ExtensionORAddressComponents_free;
asn_struct_print_f ExtensionORAddressComponents_print;
asn_constr_check_f ExtensionORAddressComponents_constraint;
ber_type_decoder_f ExtensionORAddressComponents_decode_ber;
der_type_encoder_f ExtensionORAddressComponents_encode_der;
xer_type_decoder_f ExtensionORAddressComponents_decode_xer;
xer_type_encoder_f ExtensionORAddressComponents_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtensionORAddressComponents_H_ */
#include <asn_internal.h>
