/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MiscImplicitDefinitions"
 * 	found in "MiscAttrImpl.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_Features_H_
#define	_Features_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Features */
typedef struct Features {
	A_SEQUENCE_OF(INTEGER_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Features_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Features;

#ifdef __cplusplus
}
#endif

#endif	/* _Features_H_ */
#include <asn_internal.h>
