/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms88"
 * 	found in "asn1/rfc3279-PKIX1Algorithms88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_FieldElement_H_
#define	_FieldElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FieldElement */
typedef OCTET_STRING_t	 FieldElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FieldElement;
asn_struct_free_f FieldElement_free;
asn_struct_print_f FieldElement_print;
asn_constr_check_f FieldElement_constraint;
ber_type_decoder_f FieldElement_decode_ber;
der_type_encoder_f FieldElement_encode_der;
xer_type_decoder_f FieldElement_decode_xer;
xer_type_encoder_f FieldElement_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FieldElement_H_ */
#include <asn_internal.h>
