/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "FreshestCRL.h"

int
FreshestCRL_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using CRLDistributionPoints,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_FreshestCRL_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FreshestCRL = {
	"FreshestCRL",
	"FreshestCRL",
	&asn_OP_SEQUENCE_OF,
	FreshestCRL_constraint,
	asn_DEF_FreshestCRL_tags_1,
	sizeof(asn_DEF_FreshestCRL_tags_1)
		/sizeof(asn_DEF_FreshestCRL_tags_1[0]), /* 1 */
	asn_DEF_FreshestCRL_tags_1,	/* Same as above */
	sizeof(asn_DEF_FreshestCRL_tags_1)
		/sizeof(asn_DEF_FreshestCRL_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_CRLDistributionPoints_1,
	1,	/* Single element */
	&asn_SPC_CRLDistributionPoints_specs_1	/* Additional specs */
};

