/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_FreshestCRL_H_
#define	_FreshestCRL_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRLDistributionPoints.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FreshestCRL */
typedef CRLDistributionPoints_t	 FreshestCRL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FreshestCRL;
asn_struct_free_f FreshestCRL_free;
asn_struct_print_f FreshestCRL_print;
asn_constr_check_f FreshestCRL_constraint;
ber_type_decoder_f FreshestCRL_decode_ber;
der_type_encoder_f FreshestCRL_encode_der;
xer_type_decoder_f FreshestCRL_decode_xer;
xer_type_encoder_f FreshestCRL_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FreshestCRL_H_ */
#include <asn_internal.h>
