/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "GeneralSubtree.h"

static int asn_DFL_3_set_0(int set_value, void **sptr) {
	BaseDistance_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		return asn_long2INTEGER(st, 0);
	} else {
		/* Test default value 0 */
		long value;
		if(asn_INTEGER2long(st, &value))
			return -1;
		return (value == 0);
	}
}
static asn_TYPE_member_t asn_MBR_GeneralSubtree_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralSubtree, base),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"base"
		},
	{ ATF_POINTER, 2, offsetof(struct GeneralSubtree, minimum),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BaseDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_3_set_0,	/* DEFAULT 0 */
		"minimum"
		},
	{ ATF_POINTER, 1, offsetof(struct GeneralSubtree, maximum),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BaseDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maximum"
		},
};
static const ber_tlv_tag_t asn_DEF_GeneralSubtree_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GeneralSubtree_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* otherName */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* minimum */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 1 }, /* rfc822Name */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, -1, 0 }, /* maximum */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* dNSName */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* x400Address */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* directoryName */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 }, /* ediPartyName */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* uniformResourceIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 0, 0, 0 }, /* iPAddress */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 } /* registeredID */
};
static asn_SEQUENCE_specifics_t asn_SPC_GeneralSubtree_specs_1 = {
	sizeof(struct GeneralSubtree),
	offsetof(struct GeneralSubtree, _asn_ctx),
	asn_MAP_GeneralSubtree_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GeneralSubtree = {
	"GeneralSubtree",
	"GeneralSubtree",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GeneralSubtree_tags_1,
	sizeof(asn_DEF_GeneralSubtree_tags_1)
		/sizeof(asn_DEF_GeneralSubtree_tags_1[0]), /* 1 */
	asn_DEF_GeneralSubtree_tags_1,	/* Same as above */
	sizeof(asn_DEF_GeneralSubtree_tags_1)
		/sizeof(asn_DEF_GeneralSubtree_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GeneralSubtree_1,
	3,	/* Elements count */
	&asn_SPC_GeneralSubtree_specs_1	/* Additional specs */
};

