/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "LogotypeReference.h"

static int
memb_refStructHash_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->op->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_refStructURI_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->op->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_refStructHash_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HashAlgAndValue,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_refStructHash_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_refStructHash_specs_2 = {
	sizeof(struct refStructHash),
	offsetof(struct refStructHash, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_refStructHash_2 = {
	"refStructHash",
	"refStructHash",
	&asn_OP_SEQUENCE_OF,
	SEQUENCE_OF_constraint,
	asn_DEF_refStructHash_tags_2,
	sizeof(asn_DEF_refStructHash_tags_2)
		/sizeof(asn_DEF_refStructHash_tags_2[0]), /* 1 */
	asn_DEF_refStructHash_tags_2,	/* Same as above */
	sizeof(asn_DEF_refStructHash_tags_2)
		/sizeof(asn_DEF_refStructHash_tags_2[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_refStructHash_2,
	1,	/* Single element */
	&asn_SPC_refStructHash_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_refStructURI_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_refStructURI_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_refStructURI_specs_4 = {
	sizeof(struct refStructURI),
	offsetof(struct refStructURI, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_refStructURI_4 = {
	"refStructURI",
	"refStructURI",
	&asn_OP_SEQUENCE_OF,
	SEQUENCE_OF_constraint,
	asn_DEF_refStructURI_tags_4,
	sizeof(asn_DEF_refStructURI_tags_4)
		/sizeof(asn_DEF_refStructURI_tags_4[0]), /* 1 */
	asn_DEF_refStructURI_tags_4,	/* Same as above */
	sizeof(asn_DEF_refStructURI_tags_4)
		/sizeof(asn_DEF_refStructURI_tags_4[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_refStructURI_4,
	1,	/* Single element */
	&asn_SPC_refStructURI_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LogotypeReference_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeReference, refStructHash),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_refStructHash_2,
		0,
		memb_refStructHash_constraint_1,
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"refStructHash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeReference, refStructURI),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_refStructURI_4,
		0,
		memb_refStructURI_constraint_1,
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"refStructURI"
		},
};
static const ber_tlv_tag_t asn_DEF_LogotypeReference_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeReference_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* refStructHash */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* refStructURI */
};
asn_SEQUENCE_specifics_t asn_SPC_LogotypeReference_specs_1 = {
	sizeof(struct LogotypeReference),
	offsetof(struct LogotypeReference, _asn_ctx),
	asn_MAP_LogotypeReference_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeReference = {
	"LogotypeReference",
	"LogotypeReference",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_LogotypeReference_tags_1,
	sizeof(asn_DEF_LogotypeReference_tags_1)
		/sizeof(asn_DEF_LogotypeReference_tags_1[0]), /* 1 */
	asn_DEF_LogotypeReference_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogotypeReference_tags_1)
		/sizeof(asn_DEF_LogotypeReference_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_LogotypeReference_1,
	2,	/* Elements count */
	&asn_SPC_LogotypeReference_specs_1	/* Additional specs */
};

