/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "LogotypeImage.h"

asn_TYPE_member_t asn_MBR_LogotypeImage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeImage, imageDetails),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogotypeDetails,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageDetails"
		},
	{ ATF_POINTER, 1, offsetof(struct LogotypeImage, imageInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogotypeImageInfo,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_LogotypeImage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeImage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* imageDetails */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* imageInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_LogotypeImage_specs_1 = {
	sizeof(struct LogotypeImage),
	offsetof(struct LogotypeImage, _asn_ctx),
	asn_MAP_LogotypeImage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeImage = {
	"LogotypeImage",
	"LogotypeImage",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_LogotypeImage_tags_1,
	sizeof(asn_DEF_LogotypeImage_tags_1)
		/sizeof(asn_DEF_LogotypeImage_tags_1[0]), /* 1 */
	asn_DEF_LogotypeImage_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogotypeImage_tags_1)
		/sizeof(asn_DEF_LogotypeImage_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_LogotypeImage_1,
	2,	/* Elements count */
	&asn_SPC_LogotypeImage_specs_1	/* Additional specs */
};

