/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "LogotypeImageResolution.h"

asn_TYPE_member_t asn_MBR_LogotypeImageResolution_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeImageResolution, choice.numBits),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numBits"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeImageResolution, choice.tableSize),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tableSize"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeImageResolution_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* numBits */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* tableSize */
};
asn_CHOICE_specifics_t asn_SPC_LogotypeImageResolution_specs_1 = {
	sizeof(struct LogotypeImageResolution),
	offsetof(struct LogotypeImageResolution, _asn_ctx),
	offsetof(struct LogotypeImageResolution, present),
	sizeof(((struct LogotypeImageResolution *)0)->present),
	asn_MAP_LogotypeImageResolution_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeImageResolution = {
	"LogotypeImageResolution",
	"LogotypeImageResolution",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_LogotypeImageResolution_1,
	2,	/* Elements count */
	&asn_SPC_LogotypeImageResolution_specs_1	/* Additional specs */
};

