/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_LogotypeReference_H_
#define	_LogotypeReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HashAlgAndValue;

/* LogotypeReference */
typedef struct LogotypeReference {
	struct refStructHash {
		A_SEQUENCE_OF(struct HashAlgAndValue) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} refStructHash;
	struct refStructURI {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} refStructURI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogotypeReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogotypeReference;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "HashAlgAndValue.h"

#endif	/* _LogotypeReference_H_ */
#include <asn_internal.h>
