/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "LogotypeAudioInfo.h"

static asn_TYPE_member_t asn_MBR_LogotypeAudioInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeAudioInfo, fileSize),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fileSize"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeAudioInfo, playTime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"playTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeAudioInfo, channels),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"channels"
		},
	{ ATF_POINTER, 2, offsetof(struct LogotypeAudioInfo, sampleRate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sampleRate"
		},
	{ ATF_POINTER, 1, offsetof(struct LogotypeAudioInfo, language),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"language"
		},
};
static const ber_tlv_tag_t asn_DEF_LogotypeAudioInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeAudioInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* fileSize */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* playTime */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 }, /* channels */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sampleRate */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* language */
};
static asn_SEQUENCE_specifics_t asn_SPC_LogotypeAudioInfo_specs_1 = {
	sizeof(struct LogotypeAudioInfo),
	offsetof(struct LogotypeAudioInfo, _asn_ctx),
	asn_MAP_LogotypeAudioInfo_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeAudioInfo = {
	"LogotypeAudioInfo",
	"LogotypeAudioInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LogotypeAudioInfo_tags_1,
	sizeof(asn_DEF_LogotypeAudioInfo_tags_1)
		/sizeof(asn_DEF_LogotypeAudioInfo_tags_1[0]), /* 1 */
	asn_DEF_LogotypeAudioInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogotypeAudioInfo_tags_1)
		/sizeof(asn_DEF_LogotypeAudioInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LogotypeAudioInfo_1,
	5,	/* Elements count */
	&asn_SPC_LogotypeAudioInfo_specs_1	/* Additional specs */
};

