/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_PostalAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_PKCS9String;
extern struct asn_TYPE_descriptor_s asn_DEF_Features;
extern struct asn_TYPE_descriptor_s asn_DEF_SMIMECapability;
extern struct asn_TYPE_descriptor_s asn_DEF_SMIMECapabilities;
extern struct asn_TYPE_descriptor_s asn_DEF_DSAPublicKey;
extern struct asn_TYPE_descriptor_s asn_DEF_Dss_Parms;
extern struct asn_TYPE_descriptor_s asn_DEF_Dss_Sig_Value;
extern struct asn_TYPE_descriptor_s asn_DEF_RSAPublicKey;
extern struct asn_TYPE_descriptor_s asn_DEF_DHPublicKey;
extern struct asn_TYPE_descriptor_s asn_DEF_DomainParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidationParms;
extern struct asn_TYPE_descriptor_s asn_DEF_KEA_Parms_Id;
extern struct asn_TYPE_descriptor_s asn_DEF_FieldID;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDSA_Sig_Value;
extern struct asn_TYPE_descriptor_s asn_DEF_Prime_p;
extern struct asn_TYPE_descriptor_s asn_DEF_Characteristic_two;
extern struct asn_TYPE_descriptor_s asn_DEF_Trinomial;
extern struct asn_TYPE_descriptor_s asn_DEF_Pentanomial;
extern struct asn_TYPE_descriptor_s asn_DEF_FieldElement;
extern struct asn_TYPE_descriptor_s asn_DEF_ECPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_EcpkParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_ECParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_ECPVer;
extern struct asn_TYPE_descriptor_s asn_DEF_Curve;
extern struct asn_TYPE_descriptor_s asn_DEF_Attribute;
extern struct asn_TYPE_descriptor_s asn_DEF_AttributeType;
extern struct asn_TYPE_descriptor_s asn_DEF_AttributeValue;
extern struct asn_TYPE_descriptor_s asn_DEF_AttributeTypeAndValue;
extern struct asn_TYPE_descriptor_s asn_DEF_X520name;
extern struct asn_TYPE_descriptor_s asn_DEF_X520CommonName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520LocalityName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520StateOrProvinceName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520OrganizationName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520OrganizationalUnitName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520Title;
extern struct asn_TYPE_descriptor_s asn_DEF_X520dnQualifier;
extern struct asn_TYPE_descriptor_s asn_DEF_X520countryName;
extern struct asn_TYPE_descriptor_s asn_DEF_X520SerialNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_X520Pseudonym;
extern struct asn_TYPE_descriptor_s asn_DEF_DomainComponent;
extern struct asn_TYPE_descriptor_s asn_DEF_EmailAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_Name;
extern struct asn_TYPE_descriptor_s asn_DEF_RDNSequence;
extern struct asn_TYPE_descriptor_s asn_DEF_DistinguishedName;
extern struct asn_TYPE_descriptor_s asn_DEF_RelativeDistinguishedName;
extern struct asn_TYPE_descriptor_s asn_DEF_DirectoryString;
extern struct asn_TYPE_descriptor_s asn_DEF_Certificate;
extern struct asn_TYPE_descriptor_s asn_DEF_TBSCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_Version;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateSerialNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_Validity;
extern struct asn_TYPE_descriptor_s asn_DEF_Time;
extern struct asn_TYPE_descriptor_s asn_DEF_UniqueIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectPublicKeyInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_Extensions;
extern struct asn_TYPE_descriptor_s asn_DEF_Extension;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateList;
extern struct asn_TYPE_descriptor_s asn_DEF_TBSCertList;
extern struct asn_TYPE_descriptor_s asn_DEF_AlgorithmIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_ORAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_BuiltInStandardAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryName;
extern struct asn_TYPE_descriptor_s asn_DEF_AdministrationDomainName;
extern struct asn_TYPE_descriptor_s asn_DEF_NetworkAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_X121Address;
extern struct asn_TYPE_descriptor_s asn_DEF_TerminalIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivateDomainName;
extern struct asn_TYPE_descriptor_s asn_DEF_OrganizationName;
extern struct asn_TYPE_descriptor_s asn_DEF_NumericUserIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalName;
extern struct asn_TYPE_descriptor_s asn_DEF_OrganizationalUnitNames;
extern struct asn_TYPE_descriptor_s asn_DEF_OrganizationalUnitName;
extern struct asn_TYPE_descriptor_s asn_DEF_BuiltInDomainDefinedAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_BuiltInDomainDefinedAttribute;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtensionAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtensionAttribute;
extern struct asn_TYPE_descriptor_s asn_DEF_CommonName;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexCommonName;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexOrganizationName;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexPersonalName;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexOrganizationalUnitNames;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexOrganizationalUnitName;
extern struct asn_TYPE_descriptor_s asn_DEF_PDSName;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalDeliveryCountryName;
extern struct asn_TYPE_descriptor_s asn_DEF_PostalCode;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalDeliveryOfficeName;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalDeliveryOfficeNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtensionORAddressComponents;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalDeliveryPersonalName;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalDeliveryOrganizationName;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtensionPhysicalDeliveryAddressComponents;
extern struct asn_TYPE_descriptor_s asn_DEF_UnformattedPostalAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_StreetAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_PostOfficeBoxAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_PosteRestanteAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_UniquePostalName;
extern struct asn_TYPE_descriptor_s asn_DEF_LocalPostalAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_PDSParameter;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtendedNetworkAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_PresentationAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_TerminalType;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexDomainDefinedAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_TeletexDomainDefinedAttribute;
extern struct asn_TYPE_descriptor_s asn_DEF_AuthorityKeyIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectKeyIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyUsage;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivateKeyUsagePeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificatePolicies;
extern struct asn_TYPE_descriptor_s asn_DEF_PolicyInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_CertPolicyId;
extern struct asn_TYPE_descriptor_s asn_DEF_PolicyQualifierInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PolicyQualifierId;
extern struct asn_TYPE_descriptor_s asn_DEF_CPSuri;
extern struct asn_TYPE_descriptor_s asn_DEF_UserNotice;
extern struct asn_TYPE_descriptor_s asn_DEF_NoticeReference;
extern struct asn_TYPE_descriptor_s asn_DEF_DisplayText;
extern struct asn_TYPE_descriptor_s asn_DEF_PolicyMappings;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectAltName;
extern struct asn_TYPE_descriptor_s asn_DEF_GeneralNames;
extern struct asn_TYPE_descriptor_s asn_DEF_GeneralName;
extern struct asn_TYPE_descriptor_s asn_DEF_AnotherName;
extern struct asn_TYPE_descriptor_s asn_DEF_EDIPartyName;
extern struct asn_TYPE_descriptor_s asn_DEF_IssuerAltName;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectDirectoryAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicConstraints;
extern struct asn_TYPE_descriptor_s asn_DEF_NameConstraints;
extern struct asn_TYPE_descriptor_s asn_DEF_GeneralSubtrees;
extern struct asn_TYPE_descriptor_s asn_DEF_GeneralSubtree;
extern struct asn_TYPE_descriptor_s asn_DEF_BaseDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_PolicyConstraints;
extern struct asn_TYPE_descriptor_s asn_DEF_SkipCerts;
extern struct asn_TYPE_descriptor_s asn_DEF_CRLDistributionPoints;
extern struct asn_TYPE_descriptor_s asn_DEF_DistributionPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_DistributionPointName;
extern struct asn_TYPE_descriptor_s asn_DEF_ReasonFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtKeyUsageSyntax;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyPurposeId;
extern struct asn_TYPE_descriptor_s asn_DEF_InhibitAnyPolicy;
extern struct asn_TYPE_descriptor_s asn_DEF_FreshestCRL;
extern struct asn_TYPE_descriptor_s asn_DEF_AuthorityInfoAccessSyntax;
extern struct asn_TYPE_descriptor_s asn_DEF_AccessDescription;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectInfoAccessSyntax;
extern struct asn_TYPE_descriptor_s asn_DEF_CRLNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_IssuingDistributionPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_BaseCRLNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_CRLReason;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateIssuer;
extern struct asn_TYPE_descriptor_s asn_DEF_HoldInstructionCode;
extern struct asn_TYPE_descriptor_s asn_DEF_InvalidityDate;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeExtn;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeData;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeImage;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeAudio;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeImageInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeImageType;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeImageResolution;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeAudioInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_OtherLogotypeInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_LogotypeReference;
extern struct asn_TYPE_descriptor_s asn_DEF_HashAlgAndValue;
extern struct asn_TYPE_descriptor_s asn_DEF_DateOfBirth;
extern struct asn_TYPE_descriptor_s asn_DEF_PlaceOfBirth;
extern struct asn_TYPE_descriptor_s asn_DEF_Gender;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryOfCitizenship;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryOfResidence;
extern struct asn_TYPE_descriptor_s asn_DEF_BiometricSyntax;
extern struct asn_TYPE_descriptor_s asn_DEF_BiometricData;
extern struct asn_TYPE_descriptor_s asn_DEF_TypeOfBiometricData;
extern struct asn_TYPE_descriptor_s asn_DEF_PredefinedBiometricType;
extern struct asn_TYPE_descriptor_s asn_DEF_QCStatements;
extern struct asn_TYPE_descriptor_s asn_DEF_QCStatement;
extern struct asn_TYPE_descriptor_s asn_DEF_SemanticsInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_NameRegistrationAuthorities;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module MiscAttributeForDistinguishedNames in asn1/MiscAttr.asn1 */
	&asn_DEF_PostalAddress,	
	/* From module MiscImplicitDefinitions in asn1/MiscAttrImpl.asn1 */
	&asn_DEF_PKCS9String,	
	&asn_DEF_Features,	
	/* From module SecureMimeMessageV3dot1 in asn1/pkix-smimecaps.asn1 */
	&asn_DEF_SMIMECapability,	
	&asn_DEF_SMIMECapabilities,	
	/* From module PKIX1Algorithms88 in asn1/rfc3279-PKIX1Algorithms88.asn1 */
	&asn_DEF_DSAPublicKey,	
	&asn_DEF_Dss_Parms,	
	&asn_DEF_Dss_Sig_Value,	
	&asn_DEF_RSAPublicKey,	
	&asn_DEF_DHPublicKey,	
	&asn_DEF_DomainParameters,	
	&asn_DEF_ValidationParms,	
	&asn_DEF_KEA_Parms_Id,	
	&asn_DEF_FieldID,	
	&asn_DEF_ECDSA_Sig_Value,	
	&asn_DEF_Prime_p,	
	&asn_DEF_Characteristic_two,	
	&asn_DEF_Trinomial,	
	&asn_DEF_Pentanomial,	
	&asn_DEF_FieldElement,	
	&asn_DEF_ECPoint,	
	&asn_DEF_EcpkParameters,	
	&asn_DEF_ECParameters,	
	&asn_DEF_ECPVer,	
	&asn_DEF_Curve,	
	/* From module PKIX1Explicit88 in asn1/rfc3280-PKIX1Explicit88.asn1 */
	&asn_DEF_Attribute,	
	&asn_DEF_AttributeType,	
	&asn_DEF_AttributeValue,	
	&asn_DEF_AttributeTypeAndValue,	
	&asn_DEF_X520name,	
	&asn_DEF_X520CommonName,	
	&asn_DEF_X520LocalityName,	
	&asn_DEF_X520StateOrProvinceName,	
	&asn_DEF_X520OrganizationName,	
	&asn_DEF_X520OrganizationalUnitName,	
	&asn_DEF_X520Title,	
	&asn_DEF_X520dnQualifier,	
	&asn_DEF_X520countryName,	
	&asn_DEF_X520SerialNumber,	
	&asn_DEF_X520Pseudonym,	
	&asn_DEF_DomainComponent,	
	&asn_DEF_EmailAddress,	
	&asn_DEF_Name,	
	&asn_DEF_RDNSequence,	
	&asn_DEF_DistinguishedName,	
	&asn_DEF_RelativeDistinguishedName,	
	&asn_DEF_DirectoryString,	
	&asn_DEF_Certificate,	
	&asn_DEF_TBSCertificate,	
	&asn_DEF_Version,	
	&asn_DEF_CertificateSerialNumber,	
	&asn_DEF_Validity,	
	&asn_DEF_Time,	
	&asn_DEF_UniqueIdentifier,	
	&asn_DEF_SubjectPublicKeyInfo,	
	&asn_DEF_Extensions,	
	&asn_DEF_Extension,	
	&asn_DEF_CertificateList,	
	&asn_DEF_TBSCertList,	
	&asn_DEF_AlgorithmIdentifier,	
	&asn_DEF_ORAddress,	
	&asn_DEF_BuiltInStandardAttributes,	
	&asn_DEF_CountryName,	
	&asn_DEF_AdministrationDomainName,	
	&asn_DEF_NetworkAddress,	
	&asn_DEF_X121Address,	
	&asn_DEF_TerminalIdentifier,	
	&asn_DEF_PrivateDomainName,	
	&asn_DEF_OrganizationName,	
	&asn_DEF_NumericUserIdentifier,	
	&asn_DEF_PersonalName,	
	&asn_DEF_OrganizationalUnitNames,	
	&asn_DEF_OrganizationalUnitName,	
	&asn_DEF_BuiltInDomainDefinedAttributes,	
	&asn_DEF_BuiltInDomainDefinedAttribute,	
	&asn_DEF_ExtensionAttributes,	
	&asn_DEF_ExtensionAttribute,	
	&asn_DEF_CommonName,	
	&asn_DEF_TeletexCommonName,	
	&asn_DEF_TeletexOrganizationName,	
	&asn_DEF_TeletexPersonalName,	
	&asn_DEF_TeletexOrganizationalUnitNames,	
	&asn_DEF_TeletexOrganizationalUnitName,	
	&asn_DEF_PDSName,	
	&asn_DEF_PhysicalDeliveryCountryName,	
	&asn_DEF_PostalCode,	
	&asn_DEF_PhysicalDeliveryOfficeName,	
	&asn_DEF_PhysicalDeliveryOfficeNumber,	
	&asn_DEF_ExtensionORAddressComponents,	
	&asn_DEF_PhysicalDeliveryPersonalName,	
	&asn_DEF_PhysicalDeliveryOrganizationName,	
	&asn_DEF_ExtensionPhysicalDeliveryAddressComponents,	
	&asn_DEF_UnformattedPostalAddress,	
	&asn_DEF_StreetAddress,	
	&asn_DEF_PostOfficeBoxAddress,	
	&asn_DEF_PosteRestanteAddress,	
	&asn_DEF_UniquePostalName,	
	&asn_DEF_LocalPostalAttributes,	
	&asn_DEF_PDSParameter,	
	&asn_DEF_ExtendedNetworkAddress,	
	&asn_DEF_PresentationAddress,	
	&asn_DEF_TerminalType,	
	&asn_DEF_TeletexDomainDefinedAttributes,	
	&asn_DEF_TeletexDomainDefinedAttribute,	
	/* From module PKIX1Implicit88 in asn1/rfc3280-PKIX1Implicit88.asn1 */
	&asn_DEF_AuthorityKeyIdentifier,	
	&asn_DEF_KeyIdentifier,	
	&asn_DEF_SubjectKeyIdentifier,	
	&asn_DEF_KeyUsage,	
	&asn_DEF_PrivateKeyUsagePeriod,	
	&asn_DEF_CertificatePolicies,	
	&asn_DEF_PolicyInformation,	
	&asn_DEF_CertPolicyId,	
	&asn_DEF_PolicyQualifierInfo,	
	&asn_DEF_PolicyQualifierId,	
	&asn_DEF_CPSuri,	
	&asn_DEF_UserNotice,	
	&asn_DEF_NoticeReference,	
	&asn_DEF_DisplayText,	
	&asn_DEF_PolicyMappings,	
	&asn_DEF_SubjectAltName,	
	&asn_DEF_GeneralNames,	
	&asn_DEF_GeneralName,	
	&asn_DEF_AnotherName,	
	&asn_DEF_EDIPartyName,	
	&asn_DEF_IssuerAltName,	
	&asn_DEF_SubjectDirectoryAttributes,	
	&asn_DEF_BasicConstraints,	
	&asn_DEF_NameConstraints,	
	&asn_DEF_GeneralSubtrees,	
	&asn_DEF_GeneralSubtree,	
	&asn_DEF_BaseDistance,	
	&asn_DEF_PolicyConstraints,	
	&asn_DEF_SkipCerts,	
	&asn_DEF_CRLDistributionPoints,	
	&asn_DEF_DistributionPoint,	
	&asn_DEF_DistributionPointName,	
	&asn_DEF_ReasonFlags,	
	&asn_DEF_ExtKeyUsageSyntax,	
	&asn_DEF_KeyPurposeId,	
	&asn_DEF_InhibitAnyPolicy,	
	&asn_DEF_FreshestCRL,	
	&asn_DEF_AuthorityInfoAccessSyntax,	
	&asn_DEF_AccessDescription,	
	&asn_DEF_SubjectInfoAccessSyntax,	
	&asn_DEF_CRLNumber,	
	&asn_DEF_IssuingDistributionPoint,	
	&asn_DEF_BaseCRLNumber,	
	&asn_DEF_CRLReason,	
	&asn_DEF_CertificateIssuer,	
	&asn_DEF_HoldInstructionCode,	
	&asn_DEF_InvalidityDate,	
	/* From module LogotypeCertExtn in asn1/rfc3709-LogotypeCertExtn.asn1 */
	&asn_DEF_LogotypeExtn,	
	&asn_DEF_LogotypeInfo,	
	&asn_DEF_LogotypeData,	
	&asn_DEF_LogotypeImage,	
	&asn_DEF_LogotypeAudio,	
	&asn_DEF_LogotypeDetails,	
	&asn_DEF_LogotypeImageInfo,	
	&asn_DEF_LogotypeImageType,	
	&asn_DEF_LogotypeImageResolution,	
	&asn_DEF_LogotypeAudioInfo,	
	&asn_DEF_OtherLogotypeInfo,	
	&asn_DEF_LogotypeReference,	
	&asn_DEF_HashAlgAndValue,	
	/* From module PKIXqualified88 in asn1/rfc3739-PKIXqualified88.asn1 */
	&asn_DEF_DateOfBirth,	
	&asn_DEF_PlaceOfBirth,	
	&asn_DEF_Gender,	
	&asn_DEF_CountryOfCitizenship,	
	&asn_DEF_CountryOfResidence,	
	&asn_DEF_BiometricSyntax,	
	&asn_DEF_BiometricData,	
	&asn_DEF_TypeOfBiometricData,	
	&asn_DEF_PredefinedBiometricType,	
	&asn_DEF_QCStatements,	
	&asn_DEF_QCStatement,	
	&asn_DEF_SemanticsInformation,	
	&asn_DEF_NameRegistrationAuthorities,	
	0
};

