/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MiscImplicitDefinitions"
 * 	found in "MiscAttrImpl.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_PKCS9String_H_
#define	_PKCS9String_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include "DirectoryString.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKCS9String_PR {
	PKCS9String_PR_NOTHING,	/* No components present */
	PKCS9String_PR_ia5String,
	PKCS9String_PR_directoryString
} PKCS9String_PR;

/* PKCS9String */
typedef struct PKCS9String {
	PKCS9String_PR present;
	union PKCS9String_u {
		IA5String_t	 ia5String;
		DirectoryString_t	 directoryString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS9String_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS9String;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS9String_H_ */
#include <asn_internal.h>
