/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "PolicyConstraints.h"

static asn_TYPE_member_t asn_MBR_PolicyConstraints_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PolicyConstraints, requireExplicitPolicy),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SkipCerts,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requireExplicitPolicy"
		},
	{ ATF_POINTER, 1, offsetof(struct PolicyConstraints, inhibitPolicyMapping),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SkipCerts,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inhibitPolicyMapping"
		},
};
static const ber_tlv_tag_t asn_DEF_PolicyConstraints_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PolicyConstraints_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requireExplicitPolicy */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* inhibitPolicyMapping */
};
static asn_SEQUENCE_specifics_t asn_SPC_PolicyConstraints_specs_1 = {
	sizeof(struct PolicyConstraints),
	offsetof(struct PolicyConstraints, _asn_ctx),
	asn_MAP_PolicyConstraints_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PolicyConstraints = {
	"PolicyConstraints",
	"PolicyConstraints",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_PolicyConstraints_tags_1,
	sizeof(asn_DEF_PolicyConstraints_tags_1)
		/sizeof(asn_DEF_PolicyConstraints_tags_1[0]), /* 1 */
	asn_DEF_PolicyConstraints_tags_1,	/* Same as above */
	sizeof(asn_DEF_PolicyConstraints_tags_1)
		/sizeof(asn_DEF_PolicyConstraints_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_PolicyConstraints_1,
	2,	/* Elements count */
	&asn_SPC_PolicyConstraints_specs_1	/* Additional specs */
};

