/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MiscAttributeForDistinguishedNames"
 * 	found in "MiscAttr.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_PostalAddress_H_
#define	_PostalAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DirectoryString;

/* PostalAddress */
typedef struct PostalAddress {
	A_SEQUENCE_OF(struct DirectoryString) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PostalAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PostalAddress;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DirectoryString.h"

#endif	/* _PostalAddress_H_ */
#include <asn_internal.h>
