/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_PredefinedBiometricType_H_
#define	_PredefinedBiometricType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PredefinedBiometricType {
	PredefinedBiometricType_picture	= 0,
	PredefinedBiometricType_handwritten_signature	= 1
} e_PredefinedBiometricType;

/* PredefinedBiometricType */
typedef long	 PredefinedBiometricType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PredefinedBiometricType;
asn_struct_free_f PredefinedBiometricType_free;
asn_struct_print_f PredefinedBiometricType_print;
asn_constr_check_f PredefinedBiometricType_constraint;
ber_type_decoder_f PredefinedBiometricType_decode_ber;
der_type_encoder_f PredefinedBiometricType_encode_der;
xer_type_decoder_f PredefinedBiometricType_decode_xer;
xer_type_encoder_f PredefinedBiometricType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PredefinedBiometricType_H_ */
#include <asn_internal.h>
