/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc3280-PKIX1Explicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "PresentationAddress.h"

static int
memb_nAddresses_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSET_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_nAddresses_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_nAddresses_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nAddresses_specs_5 = {
	sizeof(struct nAddresses),
	offsetof(struct nAddresses, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nAddresses_5 = {
	"nAddresses",
	"nAddresses",
	&asn_OP_SET_OF,
	SET_OF_constraint,
	asn_DEF_nAddresses_tags_5,
	sizeof(asn_DEF_nAddresses_tags_5)
		/sizeof(asn_DEF_nAddresses_tags_5[0]), /* 2 */
	asn_DEF_nAddresses_tags_5,	/* Same as above */
	sizeof(asn_DEF_nAddresses_tags_5)
		/sizeof(asn_DEF_nAddresses_tags_5[0]), /* 2 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_nAddresses_5,
	1,	/* Single element */
	&asn_SPC_nAddresses_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PresentationAddress_1[] = {
	{ ATF_POINTER, 3, offsetof(struct PresentationAddress, pSelector),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pSelector"
		},
	{ ATF_POINTER, 2, offsetof(struct PresentationAddress, sSelector),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sSelector"
		},
	{ ATF_POINTER, 1, offsetof(struct PresentationAddress, tSelector),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tSelector"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PresentationAddress, nAddresses),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_nAddresses_5,
		0,
		memb_nAddresses_constraint_1,
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nAddresses"
		},
};
static const ber_tlv_tag_t asn_DEF_PresentationAddress_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PresentationAddress_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pSelector */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sSelector */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tSelector */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nAddresses */
};
asn_SEQUENCE_specifics_t asn_SPC_PresentationAddress_specs_1 = {
	sizeof(struct PresentationAddress),
	offsetof(struct PresentationAddress, _asn_ctx),
	asn_MAP_PresentationAddress_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PresentationAddress = {
	"PresentationAddress",
	"PresentationAddress",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_PresentationAddress_tags_1,
	sizeof(asn_DEF_PresentationAddress_tags_1)
		/sizeof(asn_DEF_PresentationAddress_tags_1[0]), /* 1 */
	asn_DEF_PresentationAddress_tags_1,	/* Same as above */
	sizeof(asn_DEF_PresentationAddress_tags_1)
		/sizeof(asn_DEF_PresentationAddress_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_PresentationAddress_1,
	4,	/* Elements count */
	&asn_SPC_PresentationAddress_specs_1	/* Additional specs */
};

