/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_SkipCerts_H_
#define	_SkipCerts_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SkipCerts */
typedef INTEGER_t	 SkipCerts_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SkipCerts;
asn_struct_free_f SkipCerts_free;
asn_struct_print_f SkipCerts_print;
asn_constr_check_f SkipCerts_constraint;
ber_type_decoder_f SkipCerts_decode_ber;
der_type_encoder_f SkipCerts_encode_der;
xer_type_decoder_f SkipCerts_decode_xer;
xer_type_encoder_f SkipCerts_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SkipCerts_H_ */
#include <asn_internal.h>
