/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecureMimeMessageV3dot1"
 * 	found in "pkix-smimecaps.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#include "SMIMECapability.h"

asn_TYPE_member_t asn_MBR_SMIMECapability_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SMIMECapability, capabilityID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"capabilityID"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct SMIMECapability, parameters),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parameters"
		},
};
static const ber_tlv_tag_t asn_DEF_SMIMECapability_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SMIMECapability_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* capabilityID */
};
asn_SEQUENCE_specifics_t asn_SPC_SMIMECapability_specs_1 = {
	sizeof(struct SMIMECapability),
	offsetof(struct SMIMECapability, _asn_ctx),
	asn_MAP_SMIMECapability_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SMIMECapability = {
	"SMIMECapability",
	"SMIMECapability",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_SMIMECapability_tags_1,
	sizeof(asn_DEF_SMIMECapability_tags_1)
		/sizeof(asn_DEF_SMIMECapability_tags_1[0]), /* 1 */
	asn_DEF_SMIMECapability_tags_1,	/* Same as above */
	sizeof(asn_DEF_SMIMECapability_tags_1)
		/sizeof(asn_DEF_SMIMECapability_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_SMIMECapability_1,
	2,	/* Elements count */
	&asn_SPC_SMIMECapability_specs_1	/* Additional specs */
};

