/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms88"
 * 	found in "rfc3279-PKIX1Algorithms88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types`
 */

#ifndef	_Trinomial_H_
#define	_Trinomial_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Trinomial */
typedef INTEGER_t	 Trinomial_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Trinomial;
asn_struct_free_f Trinomial_free;
asn_struct_print_f Trinomial_print;
asn_constr_check_f Trinomial_constraint;
ber_type_decoder_f Trinomial_decode_ber;
der_type_encoder_f Trinomial_encode_der;
xer_type_decoder_f Trinomial_decode_xer;
xer_type_encoder_f Trinomial_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Trinomial_H_ */
#include <asn_internal.h>
